### ISSUE TITLE
Configuring nginx.conf with default values fails with nginx_config_main_template_enable set to true

### ISSUE THREAD

**Issue by luminouw** [nginxinc/ansible-role-nginx-config#147]
### Describe the bug
I am trying to override juste one setting (`server_names_hash_bucket_size`) in the default main template.
Comments in the file state "# Defaults are the values found in a fresh NGINX installation." so I thought enabling `nginx_config_main_template_enable` and just overriding the right subkey would do the trick as it would keep the others values.

This didn't work, so I commented out my modification about the custom setting and tried to apply the role with only `nginx_config_main_template_enable` set to `true` but it fails as well.

Using the role with `nginx_config_main_template_enable` set to `true` fails with default role values.

### To reproduce
1. Deploy NGINX Config role using playbook.yml
```
- name: NGINX
  hosts: nginx
  debugger: on_failed
  become: true

  pre_tasks:
  - name: Enabling nginx_config_main_template
    set_fact:
      nginx_config_main_template_enable: true
  roles:
  - role: nginxinc.nginx
  - role: nginxinc.nginx-config
``` 
3. Output error is (with -vvv option for verbosity)
```
TASK [nginxinc.nginx-config : Dynamically generate NGINX main configuration file] ***********************************************************************************************************
task path: /home/xxx/ansible/yyy/roles/nginxinc.nginx-config/tasks/config/template-config.yml:37
fatal: [nginx_0]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'dest'"
}
```

I don't have any more info on which 'dict object' it fails on, as the task `Dynamically generate NGINX main configuration file` has fallback default values for the dest file (`/etc/nginx/nginx.conf`) and thus shouldn't fail.

### Expected behavior
Comments say "# Defaults are the values found in a fresh NGINX installation." so it should create a standard `nginx.conf` file with default values.

### Your environment:
-   main
-   Version of Ansible: `ansible 2.9.17`
-   Version of Jinja2: `2.11.2`
-   Target deployment platform: `Debian Buster`
