### ISSUE TITLE
Not a bug: basic usage question

### ISSUE THREAD

**Issue by ezekieldas** [nginxinc/ansible-role-nginx-config#207]
### Describe the bug

This is not a bug. Just a question on basic usage. New to Ansible and nginx.

### To reproduce

I want to change default root path (Apache-ism is DocumentRoot) from /usr/share/nginx/html to /var/www/html. I know the config file to change would be `/etc/nginx/conf.d/default.conf` and the section:

```
    location / {
        root   /var/www/html;
        index  index.html index.htm;
    }
```

But I can't seem to get a single change from my playbook. I'm experimenting with another issue I saw here in the github issues. I'm experimenting with this --but it does nothing. 

I realize this won't change `location /` --but it's just a starting point. 

This is how I run the playbook: `ansible-playbook nginxinc.nginx_config.yml -K`

nginxinc.nginx_config.yml:

```
- hosts: testing
  become: true
  roles:
    - {role: nginxinc.nginx_config}
  vars:
    # nginx_config_debug_output: true
    nginx_config_http_template:
      - template_file: http/default.conf.j2
        conf_file_name: 50_example.com.conf
        conf_file_location: /etc/nginx/conf.d/
        servers:
          - listen:
              - port: 8080
              - 
```

### Expected behavior

Could you show me an example of how to change `location / {  root   /var/www/html; ...`

### Your environment

- installed from ansible galaxy
- ansible        2.9.6+dfsg-1 
- ubuntu Ubuntu 20.04.3 LTS

### Additional context

None.
