### ISSUE TITLE
how to insert an if statement in the server stanza

### ISSUE THREAD

**Issue by simevo** [nginxinc/ansible-role-nginx-config#245]
how would I insert [an `if` statement](https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#if) such as:

```
if ($request_method = POST) {
    return 405;
}
```

in the `server` stanza? Thanks!

**Comment by alessfg** [comment]
You would use the `custom_directives` parameter like it's used in https://github.com/nginxinc/ansible-role-nginx-config/blob/main/molecule/default/converge.yml#L702 but in the `server` block instead.

**Comment by simevo** [comment]
many thanks! based on your tip, I fixed my issue with this code:
```yaml
- template_file: http/default.conf.j2
  deployment_location: /etc/nginx/sites-available/xxxxxxx
  config:
    servers:
      - core:
          ...
        ssl:
          ...
        locations:
          - location: /
            ...
        custom_directives:
          - if ( $host !~* ^yyyyyy.example.com$ ) { return 444; }
```

you can close this issue from my part ...

**NOTE**: the remark [here](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/defaults/main/template.yml#L685) that "_You need to add a semi-colon at the end of each directive_" is misleading; in this case the strimg must end with `}`
