### ISSUE TITLE
Templating error

### ISSUE THREAD

**Issue by tobias-reese** [nginxinc/ansible-role-nginx-config#303]
I may be using the role the wrong way. But i get a templating error while generating the nginx.conf.

### My Config
```
- hosts: webserver_true
  collections:
    - nginxinc.nginx_core
  tasks:
    - name: Install NGINX
      ansible.builtin.include_role:
        name: nginx
    - name: Install NGINX Config
      ansible.builtin.include_role:
        name: nginx_config
      vars:
        nginx_config_main_template_enable: true
        nginx_config_main_template:
          config:
            main:
              user:
                username: nginx
                group: nginx
              worker_processes: auto
              error_log:
                file: /var/log/nginx/error.log
                level: notice
              pid: /var/run/nginx.pid
            events:
              worker_connections: 1024
            http:
              include:
                - /etc/nginx/mime.types
                - /etc/nginx/conf.d/*.conf
```

### Result
Produces following error:
```
sequence item 1: expected str instance, int found. sequence item 1: expected str instance, int found
```

### Expected behavior
Should render fine.

### Your environment
- Nginx Collection 0.7.1
- nginxinc.nginx_config 0.5.2
- Ansible 2.14.0
- Jinja2 3.0.3
- Target deployment platform: Ubuntu 22.04

### Additional Information
After digging into this i found that this is caused by the following snippet:
https://github.com/nginxinc/ansible-role-nginx-config/blob/01c9e60f5e2359aed8b12b0b26bf9dfb90adac21/templates/core.j2#L111-L113
I am no jinja user but it seems that the variable substitution has to return string and not int. Switching line 112 the following version fixes the issue:
```
worker_connections {{ events['worker_connections']|string }};
```
