### ISSUE TITLE
"mappings" from the "map" directive are not applied to a resulting configuration

### ISSUE THREAD

**Issue by Uko** [nginxinc/ansible-role-nginx-config#316]
### Describe the bug

`mappings` from the `map` directive are not applied to a resulting configuration

### To reproduce

1. Given a configuration task like this
```
- name: Configure NGINX
  ansible.builtin.include_role:
    name: nginx_config
  vars:
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      - template_file: http/default.conf.j2
        deployment_location: /etc/nginx/conf.d/default.conf
        config:
          map:
            hash_bucket_size: 64
            hash_max_size: 2048
            mappings:  # Dictionary or list of dictionaries
              string: $remote_addr  # Required
              variable: $upstream  # Required
              hostnames: false  # Boolean
              volatile: false  # Boolean
              content:  # Dictionary or list of dictionaries
                - value: default
                  new_value: 0
          servers:
            - core:
                listen:
                  - port: 80
                server_name: default_server
              locations:
                - location: /
                  proxy:
                    pass: http:/localhost:3000
                    set_header:
                      field: Host
                      value: $http_host
```
2. Check the generated `/etc/nginx/conf.d/default.conf`
3. See that everything was generated well except for mappings. `map_hash_bucket_size 64;` and `map_hash_max_size 2048;` are present, but not the `map $remote_addr $upstream {...`
4. **Clarification:** initially I had a more meaninful conf that I need for grafana, but to avoid stupid mistakes I just copied default values from the template. 

### Expected behavior

I expcted to see the map directive generated according to spec
```
map $remote_addr $upstream {
  default 0;
}
```

### Your environment

- nginx_core collection 0.8.0 (specified in the collection manifest. If you need another version please tell me where to look for it)
- ansible 2.14.3
- jinja 3.1.2
- Debian 11
