### ISSUE TITLE
Nested location 

### ISSUE THREAD

**Issue by GaetanJourdan** [nginxinc/ansible-role-nginx-config#347]
Hello!
I have the impression that it is not possible to have a nested location directive within a location directive. Is this a planned feature?
Thanks :)

**Comment by alessfg** [comment]
It's not planned at this time. That being said, you should be able to define some by using the `custom_directives` parameter https://github.com/nginxinc/ansible-role-nginx-config/blob/main/templates/http/default.conf.j2#L427-L435 😄

**Comment by gimli2** [comment]
It would be nice to be able to combine things like authentication and php. The proposed way with `custon_directives` is working but definitely it is ugly hackish approach ;-)

```yaml
...
- location: ~ /foto/
  auth_basic:
    realm: "'Please log in.'"
    user_file: $document_root/foto/.htpasswd
  custom_directives:
    - "location ~ \\.php {"
    - "    include snippets/fastcgi-php.conf;"
    - "    fastcgi_pass unix:/run/php/php-fpm.sock;"
    - "}"
```
