### ISSUE TITLE
Enforcing numeric types breaks certain templating patterns.

### ISSUE THREAD

**Issue by bleetube** [nginxinc/ansible-role-nginx-config#352]
### Describe the bug

I'm unable to omit any numeric variables by default.

We currently enforce numeric types on various values, [like so](https://github.com/nginxinc/ansible-role-nginx-config/blob/92e94360d0de9e2fc54533fc74d3b1b5089632b8/templates/core.j2#L29):

```jinja
{% if main['worker_rlimit_nofile'] is defined and main['worker_rlimit_nofile'] is number %}
worker_rlimit_nofile {{ main['worker_rlimit_nofile'] }};
{% endif %}
```

The obviates the ability to use any Ansible variable magic, such as setting a default value.  As a workaround, I need to have completely separate scopes of nginx_conf variables where everything is virtually identical except for a couple of variables like this one. The normal way to resolve such duplication would be to express a omitted default, ie. `| default(omit)`, but this doesn't work even when postfixing `| int` on it.

If I'm just missing some other way to express a number variable that can also be omitted, please let me know.

### To reproduce


```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: omit test (bad result)
      debug:
        var: nginx_config_main_template.config.main
      tags: nginx_test_type
      vars:
        nginx_worker_rlimit_noprofile: 12288
        nginx_config_main_template:
          config:
            main:
              worker_rlimit_nofile: "{{ nginx_worker_rlimit_noprofile | default(omit) }}"

    - name: int test (bad result)
      debug:
        var: nginx_config_main_template.config.main
      tags: nginx_test_type
      vars:
        nginx_worker_rlimit_noprofile: 12288
        nginx_config_main_template:
          config:
            main:
              worker_rlimit_nofile: "{{ nginx_worker_rlimit_noprofile | int }}"

    - name: basic variable test (good result, but requires duplication of nginx_conf variables when hosts have different values)
      debug:
        var: nginx_config_main_template.config.main
      tags: nginx_test_type
      vars:
        nginx_worker_rlimit_noprofile: 12288
        nginx_config_main_template:
          config:
            main:
              worker_rlimit_nofile: "{{ nginx_worker_rlimit_noprofile }}"
```
Result:
```
TASK [omit test (bad result)] 
ok: [localhost] => {
    "nginx_config_main_template.config.main": {
        "worker_rlimit_nofile": "12288"
    }
}

TASK [int test (bad result)] 
ok: [localhost] => {
    "nginx_config_main_template.config.main": {
        "worker_rlimit_nofile": "12288"
    }
}

TASK [basic variable test (good result, but requires duplication of nginx_conf variables when hosts have different values)] 
ok: [localhost] => {
    "nginx_config_main_template.config.main": {
        "worker_rlimit_nofile": 12288
    }
}
```


### Expected behavior

The way this manifested for me was that my playbooks were not writing a couple of my configuration values that I had configured. I had to check the syntax, the scoping, differences between the role version here and the role from the nginx_core collection I was using, and so on. Until I finally narrowed it to this. 

### Your environment

- Version of the Ansible NGINX configuration role or specific commit
  ```yaml
    - src: https://github.com/nginxinc/ansible-role-nginx-config
      name: nginx_core.nginx_config
      version: '0.7.0'
  ```
- Version of Ansible
    ```yaml
    ansible --version                                                                                                                                                                                                                                                   ansible [core 2.15.1]
    python version = 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429] (/usr/bin/python)
    jinja version = 3.1.2
    libyaml = True
    ```
- Version of Jinja2 (if you are using any templating capability)
- Target deployment platform
Ubuntu 22.04
