### ISSUE TITLE
"AnsibleUndefinedVariable: the inline if-expression on line 9 in 'http/grpc.j2' evaluated to false and no else section was defined."}

### ISSUE THREAD

**Issue by ghomem** [nginxinc/ansible-role-nginx-config#94]
### Describe the bug
Can't apply configuration when the http section is enabled. I get the following error:

`"AnsibleUndefinedVariable: the inline if-expression on line 9 in 'http/grpc.j2' evaluated to false and no else section was defined."}`

The configuration has been copied from this example:

https://github.com/nginxinc/ansible-role-nginx-config/blob/main/molecule/default/converge.yml

### To reproduce
```
# https://github.com/nginxinc/ansible-role-nginx
- name: Install NGINX
  include_role:
    name: nginxinc.nginx
  vars:
    nginx_install_from: os_repository
    nginx_start: false
    nginx_type: opensource
    nginx_state: present

# https://github.com/nginxinc/ansible-role-nginx-config
- name: Configure NGINX
  include_role:
    name: nginxinc.nginx_config
  vars:
    nginx_config_start: false
    nginx_config_cleanup: true
    nginx_config_debug_output: true
    nginx_config_debug_tasks: true

    # top level nginx configuration
    nginx_config_main_template_enable: true
    nginx_config_main_template:
      template_file: nginx.conf.j2
      conf_file_name: nginx.conf
      conf_file_location: /etc/nginx/
      worker_connections: 1024
      http_custom_includes:
        - "/etc/nginx/sites-enabled/*.conf"
      user: www-data
      worker_processes: auto
      pid: /var/run/nginx.pid

      # http configuration section
      http_enable: true
      http_settings:
        grpc_global:
          bind:
            address: $remote_addr
            transparent: false
          buffer_size: 4k
          connect_timeout: 60s
[...]
```

### Expected behavior
I expected the configuration to apply without errors

### Your environment:
- nginxinc.nginx_config, 0.3.3
- nginxinc.nginx, 0.19.1
- ansible: 2.9.6+dfsg-1
- ubuntu 20.04

**Comment by alessfg** [comment]
Found the issue. PR coming shortly.

**Comment by ghomem** [comment]
thank you for the quick response, I will follow up the development of this issue.

**Comment by alessfg** [comment]
Can you pull from main and check if the latest PR fixed your issue? You might need to do some further tweaks to your template since there's been a few breaking changes since `0.3.3`, but hopefully the updated examples in the molecule tests should help you get there.

**Comment by ghomem** [comment]
I can, but I am still testing other configuration situations. I just found a similar situation with gzip:

```
        gzip:
          enable: true
          buffers:
            number: 32
            size: 4k
          comp_level: 1
          disable:
            - '"msie6"'
          http_version: 1.1
          min_length: 20
          proxied:
            - expired
          types:
            - text/html
          vary: false
```

```
fatal: [testing-snap05.snapview.net]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: the inline if-expression on line 27 in 'http/gzip.j2' evaluated to false and no else section was defined."}
```
Seems to be related to the "proxied" line.
